# Generated by Django 5.1.6 on 2025-08-29 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('file_number', models.CharField(max_length=100, unique=True)),
                ('renewal_date', models.DateField()),
                ('vehicle_plate', models.CharField(max_length=20, unique=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='coop.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=50, null=True)),
                ('make_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('year_model', models.PositiveIntegerField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='coop.member')),
            ],
        ),
    ]
