# Generated by Django 5.1.6 on 2025-08-30 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='vehicle_plate',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='coop.member'),
        ),
    ]
