# Generated by Django 5.2.5 on 2025-10-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='payment_types', to='coop.member'),
        ),
    ]
