# Generated by Django 5.2.5 on 2025-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_remove_member_vehicle_plate_alter_vehicle_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
