# Generated by Django 5.0.6 on 2025-11-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_paymenttype_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Member's age", null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text="Member's sex", max_length=1, null=True),
        ),
    ]
