# Generated by Django 5.2.5 on 2025-09-01 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0003_vehicle_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_receipt', models.ImageField(upload_to='documents/or/', verbose_name='Official Receipt (OR)')),
                ('certificate_of_registration', models.ImageField(upload_to='documents/cr/', verbose_name='Certificate of Registration (CR)')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='coop.vehicle')),
            ],
        ),
    ]
