# Generated by Django 5.2.5 on 2025-10-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0003_documententry_approved_at_documententry_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documententry',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='documententry',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='documententry',
            name='manager_notes',
        ),
        migrations.RemoveField(
            model_name='documententry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='documententry',
            name='uploaded_by',
        ),
    ]
