# Generated by Django 5.0.6 on 2025-11-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='is_car_wash_record',
            field=models.BooleanField(default=False, help_text='Is this a car wash record entry?'),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='is_penalty',
            field=models.BooleanField(default=False, help_text='Is this a penalty payment for non-compliance?'),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Specific vehicle for car wash record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carwash_entries', to='coop.vehicle'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='car_wash_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Penalty amount for non-compliance', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='car_wash_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum car washes required per vehicle per month', null=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='is_car_wash',
            field=models.BooleanField(default=False, help_text='Is this a car wash payment type?'),
        ),
    ]
