# Generated by Django 5.2.5 on 2025-10-20 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_remove_documententry_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documententry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documententry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documententry',
            name='manager_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documententry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='documententry',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
