# Generated by Django 5.2.5 on 2025-09-01 21:23

import coop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='certificate_of_registration',
            field=models.ImageField(upload_to=coop.models.cr_upload_path, verbose_name='Certificate of Registration (CR)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='official_receipt',
            field=models.ImageField(upload_to=coop.models.or_upload_path, verbose_name='Official Receipt (OR)'),
        ),
    ]
