# Generated by Django 5.2.5 on 2025-09-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0005_alter_document_certificate_of_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='renewal_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='document',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='coop.vehicle'),
        ),
        migrations.AlterField(
            model_name='member',
            name='renewal_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
