# Generated by Django 5.0.6 on 2025-11-08 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0005_paymententry_is_car_wash_record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_threshold', models.PositiveIntegerField(default=4, help_text='Required number of car washes per vehicle per month')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, help_text='Penalty for non-compliance (optional)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car Wash Compliance Setting',
                'verbose_name_plural': 'Car Wash Compliance Settings',
            },
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='car_wash_penalty',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='car_wash_threshold',
        ),
        migrations.AddField(
            model_name='paymententry',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Name of public customer (if not a member)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='is_public_customer',
            field=models.BooleanField(default=False, help_text='True if this is a public (non-member) car wash customer'),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Specific vehicle for car wash record (optional for public customers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carwash_entries', to='coop.vehicle'),
        ),
        migrations.AddIndex(
            model_name='paymententry',
            index=models.Index(fields=['is_public_customer'], name='coop_paymen_is_publ_5188e7_idx'),
        ),
        migrations.AddField(
            model_name='carwashcompliance',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who last updated compliance settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carwashcompliance',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carwash_compliance', to='coop.paymentyear'),
        ),
        migrations.AlterUniqueTogether(
            name='carwashcompliance',
            unique_together={('year',)},
        ),
    ]
