# Generated by Django 5.2.5 on 2025-10-26 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0005_documententry_approved_at_documententry_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documententry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
