# Generated by Django 5.0.6 on 2025-09-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0006_document_renewal_date_alter_document_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='pending_document_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='renewal_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
