# Generated by Django 5.0.6 on 2025-11-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0006_carwashcompliance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='car_wash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Service price for this car wash type (e.g., Basic=100, Premium=150)', max_digits=10, null=True),
        ),
    ]
