# Generated by Django 5.2.5 on 2025-10-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0007_paymenttype_paymententry_paymentyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymententry',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='type',
        ),
        migrations.AddField(
            model_name='paymententry',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='carry_over',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
