# Generated by Django 5.0.6 on 2025-11-10 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0007_paymenttype_car_wash_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short notification title', max_length=200)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('category', models.CharField(choices=[('user_registration', 'New User Registration'), ('document_uploaded', 'Document Uploaded'), ('renewal_urgent', 'Urgent Renewal'), ('renewal_upcoming', 'Upcoming Renewal'), ('payment_missing', 'Payment Missing'), ('carwash_noncompliance', 'Car Wash Non-Compliance'), ('batch_deadline', 'Batch Deadline'), ('system_alert', 'System Alert'), ('account_activated', 'Account Activated'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('renewal_reminder', 'Renewal Reminder'), ('renewal_due_soon', 'Renewal Due Soon'), ('payment_recorded', 'Payment Recorded'), ('carwash_reminder', 'Car Wash Reminder'), ('announcement_posted', 'New Announcement'), ('account_warning', 'Account Warning'), ('welcome_message', 'Welcome Message')], db_index=True, max_length=30)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], db_index=True, default='normal', max_length=10)),
                ('action_url', models.CharField(blank=True, help_text='URL to redirect user when notification is clicked', max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, help_text="Text for action button (e.g., 'View Document', 'Approve Now')", max_length=50, null=True)),
                ('related_object_type', models.CharField(blank=True, help_text="Type of related object (e.g., 'member', 'vehicle', 'document')", max_length=50, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date for time-sensitive notifications', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/system that triggered this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='coop_notifi_recipie_ce6c94_idx'), models.Index(fields=['recipient', 'is_read'], name='coop_notifi_recipie_c9309d_idx'), models.Index(fields=['category', '-created_at'], name='coop_notifi_categor_51bed2_idx')],
            },
        ),
    ]
