# Generated by Django 5.0.6 on 2025-09-23 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0007_vehicle_pending_document_update_vehicle_renewal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('official_receipt', models.FileField(upload_to='requests/or/')),
                ('certificate_of_registration', models.FileField(upload_to='requests/cr/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.member')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.vehicle')),
            ],
        ),
    ]
