# Generated by Django 5.0.6 on 2025-11-11 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction ID (e.g., CW-2025-00234)', max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the service was logged')),
                ('customer_type', models.CharField(choices=[('member', 'Member'), ('public', 'Public Customer')], db_index=True, help_text='Type of customer', max_length=10)),
                ('customer_name', models.CharField(blank=True, help_text='Name of public customer (if not a member)', max_length=255)),
                ('vehicle_plate', models.CharField(blank=True, help_text='Plate number for public customer vehicle', max_length=20)),
                ('service_type_name', models.CharField(help_text='Name of service type (stored for historical record)', max_length=100)),
                ('service_amount', models.DecimalField(decimal_places=2, default=0, help_text='Service fee (₱0 for member compliance services)', max_digits=10)),
                ('carwash_year', models.PositiveIntegerField(db_index=True, help_text='Year the service is recorded for')),
                ('carwash_month', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], db_index=True, help_text='Month the service is recorded for')),
                ('is_compliance', models.BooleanField(default=False, help_text='Whether this service counts toward member compliance')),
                ('compliance_status', models.CharField(blank=True, help_text="Compliance status text (e.g., 'Compliant (1/4 required)')", max_length=50)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', help_text='Service status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional comments or remarks')),
                ('logged_by', models.ForeignKey(help_text='Staff/admin who logged the service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carwash_logs_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, help_text='Member who received service (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carwash_logs', to='coop.member')),
                ('service_type', models.ForeignKey(blank=True, help_text='Type of car wash service (links to PaymentType)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carwash_logs', to='coop.paymenttype')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Vehicle that was serviced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carwash_logs', to='coop.vehicle')),
            ],
            options={
                'verbose_name': 'Car Wash Log',
                'verbose_name_plural': 'Car Wash Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'customer_type'], name='coop_carwas_timesta_22b92e_idx'), models.Index(fields=['carwash_year', 'carwash_month'], name='coop_carwas_carwash_bb1eaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogEmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the email was sent')),
                ('recipient_email', models.EmailField(help_text='Email address where logs were sent', max_length=254)),
                ('log_type', models.CharField(choices=[('payment', 'Payment Logs'), ('carwash', 'Car Wash Logs'), ('combined', 'Combined Logs')], help_text='Type of logs included in email', max_length=20)),
                ('date_range_start', models.DateField(blank=True, help_text='Start date of log range (if filtered)', null=True)),
                ('date_range_end', models.DateField(blank=True, help_text='End date of log range (if filtered)', null=True)),
                ('total_records', models.PositiveIntegerField(default=0, help_text='Number of log records included')),
                ('pdf_generated', models.BooleanField(default=False, help_text='Whether a PDF was attached')),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent Successfully'), ('failed', 'Failed')], default='sent', help_text='Email delivery status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if delivery failed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from staff')),
                ('recipient_member', models.ForeignKey(help_text='Member who received the email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_emails_received', to='coop.member')),
                ('sent_by', models.ForeignKey(help_text='Staff member who sent the email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_emails_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Email History',
                'verbose_name_plural': 'Log Email History',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at', 'log_type'], name='coop_logema_sent_at_4afdcc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction ID (e.g., PMT-2025-00123)', max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the transaction was logged')),
                ('category', models.CharField(choices=[('from_members', 'From Members'), ('other', 'Other Payments')], db_index=True, help_text='Payment category', max_length=20)),
                ('payee_name', models.CharField(blank=True, help_text='Name of person/entity making payment (for non-member payments)', max_length=255)),
                ('payment_type_name', models.CharField(help_text='Name of payment type (stored for historical record)', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in PHP', max_digits=10)),
                ('payment_year', models.PositiveIntegerField(db_index=True, help_text='Year the payment is for')),
                ('payment_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Month the payment is for (if applicable)', null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('other', 'Other')], help_text='Method of payment', max_length=20)),
                ('receipt_number', models.CharField(blank=True, help_text='Official receipt number', max_length=100)),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference or transaction reference', max_length=100)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('reversed', 'Reversed')], db_index=True, default='confirmed', help_text='Transaction status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional comments or remarks')),
                ('description', models.TextField(blank=True, help_text='Detailed description (mainly for other payments)')),
                ('logged_by', models.ForeignKey(help_text='Staff/admin who logged the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, help_text='Member who made the payment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='coop.member')),
                ('payment_type', models.ForeignKey(blank=True, help_text='Type of payment (links to PaymentType)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='coop.paymenttype')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'category'], name='coop_paymen_timesta_72a1b2_idx'), models.Index(fields=['payment_year', 'payment_month'], name='coop_paymen_payment_e86308_idx')],
            },
        ),
    ]
