# Generated by Django 5.2.5 on 2025-10-27 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0008_remove_paymententry_amount_remove_paymenttype_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymententry',
            old_name='date_recorded',
            new_name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='paymententry',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='paymententry',
            name='carry_over',
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='payment_type',
            field=models.CharField(choices=[('from_members', 'From Members'), ('other', 'Other')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
