# Generated by Django 5.2.5 on 2025-10-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0008_user_full_name_user_valid_id_clientmemberrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='valid_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ClientMemberRequest',
        ),
    ]
