# Generated by Django 5.2.5 on 2025-10-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0007_qrlogintoken'),
        ('coop', '0009_rename_date_recorded_paymententry_recorded_at_and_more'),
    ]

    operations = [
    ]
