# Generated by Django 5.0.6 on 2025-11-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0009_carwashlog_logemailhistory_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default amount for this payment type (e.g., Monthly Dues, Membership Fee)', max_digits=10, null=True),
        ),
    ]
