# Generated by Django 5.2.5 on 2025-10-16 15:58

import coop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0009_remove_member_email_remove_member_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to=coop.models.id_upload_path),
        ),
    ]
