# Generated by Django 5.2.5 on 2025-10-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0010_merge_20251030_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dormant',
            field=models.IntegerField(default=0),
        ),
    ]
