# Generated by Django 5.2.5 on 2025-10-17 10:52

import coop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0010_user_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=coop.models.profile_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
