# Generated by Django 5.2.5 on 2025-11-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0010_paymenttype_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='amount',
        ),
    ]
