# Generated by Django 5.0.6 on 2025-11-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0011_remove_paymenttype_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tin',
        ),
        migrations.AddField(
            model_name='document',
            name='mv_file_no',
            field=models.CharField(blank=True, help_text='MV File Number (alphanumeric, varies per vehicle)', max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, help_text="Member's email (overridden by user account if linked)", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Member's phone number (overridden by user account if linked)", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, help_text='Chassis number (alphanumeric, e.g., ABC2393249RDUI)', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, help_text='Engine number (alphanumeric, e.g., ABC2393249RDUI)', max_length=70, null=True),
        ),
    ]
