# Generated by Django 5.0.6 on 2025-11-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0012_remove_document_tin_document_mv_file_no_member_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Monthly amount for 'From Members' payment types (e.g., 200.00)", max_digits=10, null=True),
        ),
    ]
