# Generated by Django 5.2.5 on 2026-04-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0013_paymenttype_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('manager', 'Manager'), ('client', 'Client Member')], default='client', max_length=20),
        ),
    ]
