# Generated by Django 5.2.5 on 2026-04-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=12, help_text='How many times per year this payment is due (e.g., 12 for monthly, 3 for quarterly, 1 for yearly, etc.).'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the amount for this payment type. The yearly total will be calculated as: amount × frequency. Example: ₱200 × 3 times/year = ₱600 yearly total.', max_digits=10, null=True),
        ),
    ]
